name: Regular CI
on:
  push:
    branches:
      - main
      - next
      - "nopr/*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v6
        with:
          run_install: true
      - name: Check
        run: node --run check
      - id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
      - name: Build website
        run: node --run build:website
        env:
          WEBSITE_BASE_PATH: "/${{ steps.repository.outputs.name }}/"
          DEPLOYED_FROM_MAIN: "1"
      - name: Upload website artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: website/dist
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  update-website:
    runs-on: ubuntu-slim
    permissions:
      id-token: write
      pages: write
    needs: build-website
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
