name: Release package
on:
  push:
    branches:
      - main
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v6
        with:
          run_install: true
      - name: Create release PR or publish package
        id: changesets
        uses: changesets/action@v2
        with:
          version: node --run changeset:version
          publish: node --run changeset:publish
          commit: Version Package (${{ github.ref_name }})
          title: Version Package (${{ github.ref_name }})
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_ACCESS: public
          NPM_CONFIG_PROVENANCE: true
